export const months = [
  'Janeiro',
  'Fevereiro',
  'Março',
  'Abril',
  'Maio',
  'Junho',
  'Julho',
  'Agosto',
  'Setembro',
  'Outubro',
  'Novembro',
  'Dezembro'
];
export const monthsShort = [
  'Jan',
  'Fev',
  'Mar',
  'Abr',
  'Mai',
  'Jun',
  'Jul',
  'Ago',
  'Set',
  'Out',
  'Nov',
  'Dez'
];
export const weekDays = ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'];
export const weekDaysShort = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'];
export const meals = {
  principal: 'Principal',
  grelha: 'Na Grelha',
  vegetariano: 'Vegetariano',
  fastgrill: 'Fast Grill',
  acompanhamento: 'Acompanhamento',
  sopa: 'Sopa',
  salada: 'Salada',
  sobremesa: 'Sobremesa',
  suco: 'Suco'
};

export const AVA_URL = 'http://ava.ufrpe.br';
export const FIREBASE_URL = 'https://ufrpe-5033f.firebaseio.com/';
export const CONSTS = {
  URL_COMPLEMENT: '/webservice/rest/server.php?moodlewsrestformat=json',
  LOGIN_SERVICE: 'moodle_mobile_app',
  FUNCTION_GET_USER: 'core_user_get_users_by_id',
  FUNCTION_GET_USER_COURSES: 'core_enrol_get_users_courses',
  FUNCTION_GET_SITE_INFO: 'core_webservice_get_site_info',
  FUNCTION_GET_COURSE_CONTENTS: 'core_course_get_contents',
  FUNCTION_GET_CALENDAR_EVENTS: 'core_calendar_get_calendar_events',
  FUNCTION_GET_MESSAGES: 'core_message_get_messages',
  FUNCTION_SEND_MESSAGE: 'core_message_send_instant_messages',
  FUNCTION_GET_PARTICIPANTS: 'core_enrol_get_enrolled_users',
  FUNCTION_GET_ASSIGNMENTS: 'mod_assign_get_assignments',
  FUNCTION_GET_DISCUSSIONS: 'mod_forum_get_forum_discussions_paginated',
  FUNCTION_GET_DISCUSSIONS_POSTS: 'mod_forum_get_forum_discussion_posts',
  FUNCTION_GET_GRADES: 'gradereport_user_get_grades_table'
};

export const headers = {
  Accept: 'application/json',
  'Content-Type': 'multipart/form-data'
};

export const SEMESTER = '2017.2';

export const COLORS = {
  blue: '#1B2D4F',
  pink: '#f21e60'
};

export const COURSE_COLORS = [
  '#F44336',
  '#E91E63',
  '#9C27B0',
  '#673AB7',
  '#3F51B5',
  '#2196F3',
  '#039BE5',
  '#0097A7',
  '#009688',
  '#43A047',
  '#689F38',
  '#EF6C00',
  '#FF5722',
  '#795548',
  '#757575'
];

export const MIME_TYPES = {
  '3gp': 'file-video-o',
  aac: 'file-audio-o',
  aif: 'file-audio-o',
  aiff: 'file-audio-o',
  aifc: 'file-audio-o',
  applescript: 'file-text-o',
  asc: 'file-code-o',
  asm: 'file-code-o',
  au: 'file-audio-o',
  avi: 'file-video-o',
  bmp: 'file-image-o',
  c: 'file-code-o',
  cpp: 'file-code-o',
  cs: 'file-code-o',
  css: 'file-text-o',
  csv: 'file-excel-o',
  dv: 'file-video-o',
  doc: 'file-word-o',
  docx: 'file-word-o',
  docm: 'file-word-o',
  dotx: 'file-word-o',
  dotm: 'file-word-o',
  dif: 'file-video-o',
  fdf: 'file-pdf-o',
  gif: 'file-image-o',
  gtar: 'file-archive-o',
  tgz: 'file-archive-o',
  gz: 'file-archive-o',
  gzip: 'file-archive-o',
  h: 'file-code-o',
  hpp: 'file-code-o',
  hqx: 'file-archive-o',
  ico: 'file-image-o',
  ics: 'file-text-o',
  java: 'file-code-o',
  jpe: 'file-image-o',
  jpeg: 'file-image-o',
  jpg: 'file-image-o',
  js: 'file-text-o',
  latex: 'file-text-o',
  m: 'file-code-o',
  mov: 'file-video-o',
  movie: 'file-video-o',
  m3u: 'file-audio-o',
  mp3: 'file-audio-o',
  mp4: 'file-video-o',
  m4v: 'file-video-o',
  m4a: 'file-audio-o',
  mpeg: 'file-video-o',
  mpe: 'file-video-o',
  mpg: 'file-video-o',
  odt: 'file-word-o',
  ott: 'file-word-o',
  odm: 'file-word-o',
  oga: 'file-audio-o',
  ogg: 'file-audio-o',
  ogv: 'file-video-o',
  pct: 'file-image-o',
  pdf: 'file-pdf-o',
  php: 'file-code-o',
  pic: 'file-image-o',
  pict: 'file-image-o',
  png: 'file-image-o',
  pps: 'file-powerpoint-o',
  ppt: 'file-powerpoint-o',
  pptx: 'file-powerpoint-o',
  pptm: 'file-powerpoint-o',
  potx: 'file-powerpoint-o',
  potm: 'file-powerpoint-o',
  ppam: 'file-powerpoint-o',
  ppsx: 'file-powerpoint-o',
  ppsm: 'file-powerpoint-o',
  ps: 'file-pdf-o',
  qt: 'file-video-o',
  ra: 'file-audio-o',
  ram: 'file-audio-o',
  rm: 'file-audio-o',
  rmvb: 'file-video-o',
  rtf: 'file-text-o',
  rtx: 'file-text-o',
  rv: 'file-audio-o',
  sh: 'file-code-o',
  sit: 'file-archive-o',
  smi: 'file-text-o',
  smil: 'file-text-o',
  svg: 'file-image-o',
  svgz: 'file-image-o',
  tar: 'file-archive-o',
  tex: 'file-text-o',
  texi: 'file-text-o',
  texinfo: 'file-text-o',
  tsv: 'file-text-o',
  txt: 'file-text-o',
  webm: 'file-video-o',
  xdp: 'file-pdf-o',
  xfd: 'file-pdf-o',
  xfdf: 'file-pdf-o',
  xls: 'file-excel-o',
  xlsx: 'file-excel-o',
  xlsm: 'file-excel-o',
  xltx: 'file-excel-o',
  xltm: 'file-excel-o',
  xlsb: 'file-excel-o',
  xlam: 'file-excel-o',
  zip: 'file-archive-o',
  assign: 'check-square-o',
  assignment: 'check-square-o',
  book: 'book',
  chat: 'comments',
  choice: 'question',
  data: 'database',
  database: 'database',
  'external-tool': 'puzzle-piece',
  feedback: 'bullhorn',
  file: 'file-o',
  folder: 'folder-open-o',
  forum: 'comments-o',
  glossary: 'address-book',
  ims: 'archive',
  imscp: 'archive',
  label: 'tag',
  lesson: 'sitemap',
  lti: 'puzzle-piece',
  page: 'file-text',
  quiz: 'check',
  survey: 'line-chart',
  url: 'chrome',
  wiki: 'wikipedia-w',
  workshop: 'users'
};
